### ISSUE TITLE
Crash on map load

### ISSUE THREAD

**Issue by Orkanna** [Orkanna/Orkanna#1]
[Ported from Android Crashes & ANRs]

**Comment by AdamHirst** [comment]
Multiple crashes reported on APK v1. No reports since last week may suggest the issue was related to data, however could be a Google maps exception.

No action will be taken unless further reports are submitted.

**Comment by AdamHirst** [comment]
This issue has been reconfirmed.  This bug should be addressed with the OSM integration.
