### ISSUE TITLE
Filter menu interaction

### ISSUE THREAD

**Issue by Orkanna** [Orkanna/Orkanna#2]
The map's filter menu causes a crash when the search window is opened on top of an already opened menu.

Recreation steps:
1. Open filter menu on map screen,
2. Open the search facility using the side menu,
3. Return to the map,
4. Close the filter menu.

**Comment by AdamHirst** [comment]
Issue confirmed for APK v1. Patching for v2.

**Comment by AdamHirst** [comment]
Fixed for next release.
